apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: vite-action
  name: vite-action-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: vite-action
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: vite-action
    spec:
      containers:
        - image: asia-northeast1-docker.pkg.dev/engaged-carving-424707-n9/vite-action-repo/vite-action:v1
          name: vite-action
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: vite-action
