#pr-test.yml
name: PR Test

on:
pull_request:
  types: [opened, reopened]
  branches: [main, develop, feature, release]

jobs:
Run Jest:
  runs-on: [ubuntu-latest]
  strategy:
    matrix:
      node-version: [12.x]
  steps:
    - name: npm install
      run: npm install
    - name: run test code
      run: npm run e2e-test

    - name: if fail
      uses: actions/github-script@0.8.0
      with:
        github-token: ${{ github.token }}
        script: :|
          const ref = "${{github.ref}}"
          const pull_number = Number(ref.split("/")[2])
          await github.pulls.createReview({
          ...context.repo,
          pull_number,
          body:"테스트코드를 다시 확인해주세요. ",
          event:"REQUEST_CHANGES"
          })
          await github.pulls.update({
          ...context.repo,
          pull_number,
          state:"closed"
          })
      if: failure()
